#!/usr/bin/env bash

################################################################################
# https://peterbabic.dev/blog/make-ssh-prompt-password-keepassxc/
################################################################################

attempts=10

until ssh-add -l &> /dev/null
do
  if [[ ${attempts} -eq 0 ]]; then
    break
  fi

  echo "Waiting for agent. Please unlock the database."
  /Applications/KeePassXC.app/Contents/MacOS/keepassXC &> /dev/null
  sleep 1
  attempts=$((attempts-1))
done

/usr/bin/nc "$1" "$2"
