tap "anomalyco/tap"
tap "arkweid/lefthook"
tap "derailed/k9s"
tap "dteoh/sqa"
tap "fforster/gitlab-mcp", "https://gitlab.com/fforster/homebrew-gitlab-mcp.git"
tap "jarred-sumner/git-peek"
tap "jdxcode/tap"
tap "jstkdng/programs"
tap "leipert-projects/git-recon", "https://gitlab.com/leipert-projects/git-recon.git"
tap "lihaoyun6/tap"
tap "mike-engel/jwt-cli"
tap "minio/stable"
tap "moul/moul"
tap "mvp/uhubctl", "https://github.com/mvp/uhubctl"
tap "zaquestion/tap"
brew "agg"
brew "angle-grinder"
brew "xz"
brew "arduino-cli"
brew "asciinema"
brew "readline"
brew "bash"
brew "bat"
brew "blueutil"
brew "boost"
brew "btop"
brew "glib"
brew "harfbuzz"
brew "pango"
brew "checkmake"
brew "cmake"
brew "colima", restart_service: :changed
brew "container", link: false
brew "container-diff"
brew "coreutils"
brew "croc"
brew "ctop"
brew "curl"
brew "sqlite"
brew "dive"
brew "docker"
brew "docker-buildx"
brew "docker-credential-helper"
brew "docutils"
brew "gnu-tar"
brew "dpkg"
brew "duf"
brew "dust"
brew "duti"
brew "entr"
brew "epr"
brew "exiftool"
brew "eza"
brew "fcgiwrap"
brew "fd"
brew "ffmpeg"
brew "fio"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "gitleaks"
brew "glab"
brew "gnu-sed"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "gpgme"
brew "graphicsmagick"
brew "grc"
brew "groff"
brew "pkgconf"
brew "heimdal"
brew "helm"
brew "highlight"
brew "htop"
brew "hyperfine"
brew "iperf3"
brew "ipinfo-cli"
brew "jless"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "libiconv"
brew "libpq", link: true
brew "lnav"
brew "luarocks"
brew "lychee"
brew "mackup"
brew "markdownlint-cli"
brew "mas"
brew "ninja"
brew "meson"
brew "miller"
brew "minikube"
brew "mise"
brew "mkcert"
brew "moreutils"
brew "ncdu"
brew "neovim"
brew "neovim-remote"
brew "nginx", restart_service: :changed
brew "nmap"
brew "node_exporter", restart_service: :changed
brew "pandoc"
brew "pgcli"
brew "pgformatter"
brew "pigz"
brew "pinentry-mac"
brew "pipenv"
brew "pipx"
brew "poppler"
brew "pspg"
brew "pygments"
brew "rbspy"
brew "re2"
brew "redis"
brew "remake"
brew "ripgrep"
brew "ripsecrets"
brew "rlwrap"
brew "runit"
brew "s3cmd"
brew "sd"
brew "sevenzip"
brew "smartmontools"
brew "socat"
brew "spawn-fcgi"
brew "switchaudio-osx"
brew "tealdeer"
brew "terminal-notifier"
brew "terraform"
brew "the_silver_searcher"
brew "tokei"
brew "uhubctl"
brew "vale"
brew "viddy"
brew "vimpager"
brew "visidata"
brew "w3m"
brew "watch"
brew "wget"
brew "wifi-password"
brew "xh"
brew "yadm"
brew "yamllint"
brew "yazi"
brew "ykpers"
brew "yq"
brew "yt-dlp"
brew "zoxide"
brew "anomalyco/tap/opencode"
brew "fforster/gitlab-mcp/gitlab-mcp"
brew "jarred-sumner/git-peek/git-peek"
brew "jstkdng/programs/ueberzugpp"
brew "leipert-projects/git-recon/git-recon"
brew "mike-engel/jwt-cli/jwt-cli"
brew "moul/moul/docker-diff"
cask "1password"
cask "1password-cli"
cask "airbuddy"
cask "alfred"
cask "apparency"
cask "appcleaner"
cask "bartender"
cask "beyond-compare@4"
cask "bluesnooze"
cask "choosy"
cask "chrysalis"
cask "claude"
cask "clickhouse"
cask "container"
cask "contexts"
cask "dash"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "elgato-wave-link"
cask "eqmac"
cask "etrecheckpro"
cask "firefox"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "fork"
cask "gcloud-cli"
cask "gimp"
cask "google-chrome"
cask "home-assistant"
cask "imageoptim"
cask "input-source-pro"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kap"
cask "keycastr"
cask "keyclu"
cask "latest"
cask "libreoffice"
cask "lunar"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-edge@canary"
cask "muzzle"
cask "neovide-app"
cask "netspot"
cask "notion"
cask "p4v"
cask "plex"
cask "protonvpn"
cask "raycast"
cask "rectangle-pro"
cask "send-to-kindle"
cask "shottr"
cask "slack"
cask "spotify"
cask "superwhisper"
cask "syntax-highlight"
cask "visual-studio-code"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "Backdrop", id: 411461952
mas "DaisyDisk", id: 411643860
mas "Discovery", id: 1381004916
mas "Expressions", id: 913158085
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "Kindle", id: 302584613
mas "Mactracker", id: 430255202
mas "MediaInfo", id: 510620098
mas "MusicBuddy", id: 563706976
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Okta Verify", id: 490179405
mas "Parcel", id: 375589283
mas "PLIST Editor", id: 1157491961
mas "Speedtest", id: 1153157709
mas "WireGuard", id: 1451685025
vscode "chrischinchilla.vale-vscode"
vscode "davidanson.vscode-markdownlint"
vscode "deque-systems.vscode-axe-linter"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "gitlab.gitlab-workflow"
vscode "redhat.vscode-yaml"
vscode "shopify.ruby-lsp"
vscode "vscodevim.vim"
