#!/usr/bin/env zsh

#
# The `gf` alias fetches branches/tags from the remote, and notifying when branches have been merged

local git_cmd=git
if [[ "$PWD" == "$HOME" ]]; then
  git_cmd=yadm
fi

$git_cmd fetch --jobs=10
$git_cmd branch -vv | grep -E '(origin|security)/.*: gone]' | awk '{print $1}' | grep -v '^_.*$' | awk '{print $1 " has been merged!"}' | xargs -I _ terminal-notifier -title 'Git fetch' -message _ -sound boop -ignoreDnD
