#!/usr/bin/env zsh

if [[ "$#" -ne 0 ]]; then
  cd "$(autojump $@)"
  return
fi

cd "$(autojump -s | sort -k1gr | awk '$1 ~ /[0-9]:/ && $2 ~ /^\// { for (i=2; i<=NF; i++) { print $(i) } }' |  fzf --height 40% --reverse --inline-info)" || exit

