#!/usr/bin/env zsh

# Add a `vf` function to zsh that opens vifm either at the given directory or
# at the one autojump suggests
if [ "$2" != "" ]; then
  vifm "$@"
elif [ "$1" != "" ]; then
  if [ -d "$1" ]; then
    vifm "$1"
  elif [ -f "$1" ]; then
    vifm "$1"
  else
    out="$(autojump $1)"
    vifm "$out"
  fi
else
  dst="$(command vifm --choose-dir -)"
  if [ -z "$dst" ]; then
    echo 'Directory picking cancelled/failed'
    return 1
  fi
  cd "$dst"
fi
return $?
