gui:
    authorColors:
        "Pedro Pombeiro": "#83a598" # use a light blue for my commits
    branchColors:
        "pedropombeiro": "#83a598" # use a light blue for branches beginning with 'pedropombeiro/'
        "_pedropombeiro": "#7c6f64" # use gray for branches beginning with '_pedropombeiro/'
        "tmp": "#504945" # use dark gray for branches beginning with 'tmp/'
    mouseEvents: true
    skipDiscardChangeWarning: false
    skipStashWarning: false
    # stuff relating to the UI
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.3333 # number from 0 to 1
    expandFocusedSidePanel: false
    mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
    language: "auto" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl' | 'ja' | 'ko'
    nerdFontsVersion: "3"
    timeFormat: "02 Jan 06 15:04 MST" # https://pkg.go.dev/time#Time.Format
    theme:
        lightTheme: false
        activeBorderColor:
            - "#97971a" # green
            - bold
        inactiveBorderColor:
            - "#928374" # gray
        optionsTextColor:
            - "#8ec07c" # aqua
        selectedLineBgColor:
            - "#458588" # blue
        # selectedRangeBgColor:
        #   - '#458588'  # blue
        cherryPickedCommitBgColor:
            - "#458588" # blue
        cherryPickedCommitFgColor:
            - "#689d6a" # cyan
        unstagedChangesColor:
            - "#fb4934" # red
        defaultFgColor:
            - "#ebdbb2" # default
    commitLength:
        show: true
    skipNoStagedFilesWarning: false
    showFileTree: true # for rendering changes files in a tree format
    showListFooter: true # for seeing the '5 of 20' message in list panels
    showRandomTip: true
    showBottomLine: true # for hiding the bottom information line (unless it has important information to tell you)
    showCommandLog: true
    showIcons: true
    showDivergenceFromBaseBranch: 'arrowAndNumber'
    commandLogSize: 8
    splitDiff: "auto" # one of 'auto' | 'always'
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never --no-gitconfig --syntax-theme 'gruvbox-dark'
        useConfig: false
    commit:
        signOff: false
    merging:
        # If true, run merges in a subprocess so that if a commit message is required, Lazygit will not hang
        # Only applicable to unix users.
        manualCommit: false
        # extra args passed to `git merge`, e.g. --no-ff
        args: ""
    log:
        # one of date-order, author-date-order, topo-order.
        # topo-order makes it easier to read the git log graph, but commits may not
        # appear chronologically. See https://git-scm.com/docs/git-log#_commit_ordering
        order: "topo-order"
        # one of always, never, when-maximised
        # this determines whether the git graph is rendered in the commits panel
        showGraph: "when-maximised"
        # displays the whole git graph by default in the commits panel (equivalent to passing the `--all` argument to `git log`)
        showWholeGraph: false
    skipHookPrefix: WIP
    autoFetch: false
    autoRefresh: true
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
    allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
    overrideGpg: true # allows lazygit to spawn a separate process when using GPG
    disableForcePushing: false
    parseEmoji: false
    diffContextSize: 3 # how many lines of context are shown around a change in diffs
os:
    editPreset: 'nvim'
refresher:
    refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
    fetchInterval: 60 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.
update:
    method: prompt # can be: prompt | background | never
    days: 14 # how often an update is checked for
reporting: "undetermined" # one of: 'on' | 'off' | 'undetermined'
confirmOnQuit: false
# determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
quitOnTopLevelReturn: false
disableStartupPopups: true
notARepository: "prompt" # one of: 'prompt' | 'create' | 'skip' | 'quit'
promptToReturnFromSubprocess: false # do not display confirmation when subprocess terminates
keybinding:
    universal:
        quit: "q"
        quit-alt1: "<c-q>" # alternative/alias of quit
        return: "<esc>" # return to previous menu, will quit if there's nowhere to return
        quitWithoutChangingDirectory: "Q"
        togglePanel: "<tab>" # goto the next panel
        prevItem: "<up>" # go one line up
        nextItem: "<down>" # go one line down
        prevItem-alt: "k" # go one line up
        nextItem-alt: "j" # go one line down
        prevPage: "," # go to next page in list
        nextPage: "." # go to previous page in list
        gotoTop: "<" # go to top of list
        gotoBottom: ">" # go to bottom of list
        scrollLeft: "H" # scroll left within list view
        scrollRight: "L" # scroll right within list view
        prevBlock: "<left>" # goto the previous block / panel
        nextBlock: "<right>" # goto the next block / panel
        prevBlock-alt: "h" # goto the previous block / panel
        nextBlock-alt: "l" # goto the next block / panel
        jumpToBlock: ["1", "2", "3", "4", "5"]
        nextMatch: "n"
        prevMatch: "N"
        optionMenu: "x" # show help menu
        optionMenu-alt1: "?" # show help menu
        select: "<space>"
        goInto: "<enter>"
        openRecentRepos: "<c-r>"
        confirm: "<enter>"
        confirm-alt1: "y"
        remove: "d"
        new: "n"
        edit: "e"
        openFile: "o"
        scrollUpMain: "<pgup>" # main panel scroll up
        scrollDownMain: "<pgdown>" # main panel scroll down
        scrollUpMain-alt1: "K" # main panel scroll up
        scrollDownMain-alt1: "J" # main panel scroll down
        scrollUpMain-alt2: "<c-u>" # main panel scroll up
        scrollDownMain-alt2: "<c-d>" # main panel scroll down
        executeCustomCommand: ":"
        createRebaseOptionsMenu: "m"
        pushFiles: "P"
        pullFiles: "p"
        refresh: "R"
        createPatchOptionsMenu: "<c-p>"
        nextTab: "]"
        prevTab: "["
        nextScreenMode: "+"
        prevScreenMode: "_"
        undo: "z"
        redo: "<c-z>"
        filteringMenu: "<c-s>"
        diffingMenu: "W"
        diffingMenu-alt: "<c-e>" # deprecated
        copyToClipboard: "<c-o>"
        submitEditorText: "<enter>"
        appendNewline: "<a-enter>"
        extrasMenu: "@"
        toggleWhitespaceInDiffView: "<c-w>"
        increaseContextInDiffView: "}"
        decreaseContextInDiffView: "{"
    status:
        checkForUpdate: "u"
        recentRepos: "<enter>"
    files:
        commitChanges: "c"
        commitChangesWithoutHook: "w" # commit changes without pre-commit hook
        amendLastCommit: <disabled> # "A"
        commitChangesWithEditor: "C"
        ignoreFile: "i"
        refreshFiles: "r"
        stashAllChanges: "s"
        viewStashOptions: "S"
        toggleStagedAll: "a" # stage/unstage all
        viewResetOptions: "D"
        fetch: "f"
        toggleTreeView: "`"
    branches:
        createPullRequest: "o"
        viewPullRequestOptions: "O"
        checkoutBranchByName: "c"
        forceCheckoutBranch: "F"
        rebaseBranch: "r"
        renameBranch: "R"
        mergeIntoCurrentBranch: "M"
        viewGitFlowOptions: "i"
        fastForward: "f" # fast-forward this branch from its upstream
        pushTag: "P"
        setUpstream: "u" # set as upstream of checked-out branch
        fetchRemote: "f"
    commits:
        squashDown: "s"
        renameCommit: "r"
        renameCommitWithEditor: "R"
        viewResetOptions: "g"
        markCommitAsFixup: "f"
        createFixupCommit: "F" # create fixup commit for this commit
        squashAboveCommits: "S"
        moveDownCommit: "<c-j>" # move commit down one
        moveUpCommit: "<c-k>" # move commit up one
        amendToCommit: <disabled> # "A"
        pickCommit: "p" # pick commit (when mid-rebase)
        revertCommit: "t"
        cherryPickCopy: "c"
        cherryPickCopyRange: "C"
        pasteCommits: "v"
        tagCommit: "T"
        checkoutCommit: "<space>"
        resetCherryPick: "<c-R>"
        copyCommitMessageToClipboard: "<c-y>"
        openLogMenu: "<c-l>"
        viewBisectOptions: "b"
    stash:
        popStash: "g"
        renameStash: "r"
    commitFiles:
        checkoutCommitFile: "c"
    main:
        toggleDragSelect: "v"
        toggleDragSelect-alt: "V"
        toggleSelectHunk: "a"
        pickBothHunks: "b"
    submodules:
        init: "i"
        update: "u"
        bulkMenu: "b"
customCommands:
    - key: "A"
      context: "commits"
      command: 'git revise -- "{{.SelectedLocalCommit.Sha}}"'
      stream: true
      description: "Git-revise selected commit with staged changes"
    - key: "A"
      context: "files"
      command: 'git revise -- HEAD'
      stream: true
      description: "Git-revise last commit with staged changes"
