#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "Home Assistant config"
path = "/share/Container/config/home-assistant/config"
startup_command = "nvim -c ':lua Snacks.picker.files()'"
preview_command = "eza --all --git --icons --color=always --oneline {}"

[[session]]
name = "Docker Compose config"
path = "/share/Container/compose"
startup_command = "nvim -c ':lua Snacks.picker.files({ args = { \"-g\", \"docker-compose.yml\" } })'"
preview_command = "eza --all --git --icons --color=always --oneline {}"

[[wildcard]]
pattern = "/share/Container/compose/*"
startup_command = "nvim docker-compose.yml"
preview_command = "bat --color=always {}/docker-compose.yml"
