# Proxy external requests from Home Assistant to Hammerspoon and the Busylight HTTP server
server {
  listen      18989;
  server_name localhost;

  location /trigger {
    proxy_pass http://127.0.0.1:18990;
  }

  location / {
    proxy_pass http://localhost:8989;
  }
}
