[theme]
name = "gruvbox"

[colors]
Base = "#ebdbb2"
Title = "#fabd2f"
Important = "#fe8019"
Guidance = "#83a598"
Annotation = "#7c6f64"
Muted = "#665c54"
AlertInfo = "#b8bb26"
AlertWarn = "#fabd2f"
AlertError = "#fb4934"
