[[mgr.prepend_keymap]]
on = ["<Space>", ","]
run = "shell --block -- $EDITOR $HOME/.config/yazi/keymap.toml"

[[mgr.prepend_keymap]]
on = ["<C-q>"]
run = "quit --no-cwd-file"

[[mgr.prepend_keymap]]
on = ["<Space>", "d", "u"]
run = "shell --block -- ncdu --color dark-bg $0"

[[mgr.prepend_keymap]]
on   = ["<Space>", "<Space>"]
run  = "toggle"
desc = "Toggle selection"

[[mgr.prepend_keymap]]
on   = ["<C-t>"]
run  = "shell --block -- nvim -d $@"
desc = "Open diff in Neovim"

[[mgr.prepend_keymap]]
on = ["[", "["]
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on = ["]", "]"]
run = "plugin parent-arrow 1"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to the root of the current Git repository"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# https://github.com/dedukun/relative-motions.yazi
[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

# https://github.com/dedukun/bookmarks.yazi
[[mgr.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# https://yazi-rs.github.io/docs/tips#smart-tab
[[mgr.prepend_keymap]]
on = "t"
run = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

# https://github.com/Lil-Dank/lazygit.yazi
[[mgr.prepend_keymap]]
on = ["<Space>", "t", "g"]
run = "plugin lazygit"
desc = "Run lazygit"

# https://github.com/KKV9/command.yazi
[[mgr.prepend_keymap]]
on = ["c", "p"]
run = "plugin command"
desc = "Yazi command prompt"

# https://github.com/KKV9/compress.yazi
[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

# https://github.com/yazi-rs/plugins/tree/main/chmod.yazi
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# https://github.com/ourongxing/fast-enter.yazi
[[mgr.prepend_keymap]]
on = ["l"]
run = "plugin fast-enter"
desc = "Enter the subfolder faster, or open the file directly"

# yazi-rs/plugins:vcs-files
[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

# yazi-rs/plugins:diff
[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

# KKV9/compress.yazi
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"
