-- stylua: ignore
return {
  theme = {
    name = 'gruvbox',
    colors = {
      dark0       = '#101011',
      bg0_s       = '#32302f', -- Gruvbox Dark bg0_s
      gray        = '#928374',
      fg          = '#ebdbb2',
      fg3         = '#bdae93',
      fg4         = '#a89984',
      dark_blue   = '#83a598',
      blue        = '#458588',
      cyan        = '#8ec07c',
      green_bg    = '#98971a',
      orange_bg   = '#d65d0e',
      orange      = '#fe8019',
      dark_red    = '#fb4934',
      red         = '#cc241d',
      dark_yellow = '#fabd2f',
      green       = '#b8bb26',
      purple      = '#d3869b',
    }
  },
  ui = {
    border = 'rounded',
    icons = {
      folder = {
        empty      = '',
        empty_open = '',
        collapsed  = '',
        expanded   = '',
      },
      expander = {
        collapsed = '',
        expanded  = '',
      },
      diagnostics = {
        debug   = '',
        hint    = '',
        trace   = '✎',
        info    = '',
        warning = '',
        error   = '',
      },
      kinds = {
        Array         = ' ',
        Boolean       = '󰨙 ',
        Class         = ' ',
        Codeium       = '󰘦 ',
        Color         = ' ',
        Control       = ' ',
        Collapsed     = ' ',
        Constant      = '󰏿 ',
        Constructor   = ' ',
        Copilot       = ' ',
        Enum          = ' ',
        EnumMember    = ' ',
        Event         = ' ',
        Field         = ' ',
        File          = ' ',
        Folder        = ' ',
        Function      = '󰊕 ',
        Interface     = ' ',
        Key           = '🔑 ',
        Keyword       = ' ',
        Macro         = ' ',
        Method        = '󰊕 ',
        Module        = ' ',
        Namespace     = '󰦮 ',
        Null          = ' ',
        Number        = '󰎠 ',
        Object        = ' ',
        Operator      = ' ',
        Package       = ' ',
        Property      = ' ',
        Reference     = ' ',
        Snippet       = ' ',
        String        = ' ',
        Struct        = '󰆼 ',
        TabNine       = '󰏚 ',
        Text          = ' ',
        TypeAlias     = ' ',
        TypeParameter = ' ',
        Unit          = ' ',
        Value         = ' ',
        Variable      = '󰀫 ',
      },
      symbols = {
        added    = '',
        modified = '',
        removed  = '',
        renamed  = '󰁕',
        unstaged = '󰄱',
        readonly = '',
      },
      tests = {
        passed     = '',
        running    = '',
        failed     = '',
        cancelled  = '⊘',
        skipped    = '◌',
        unknown    = ''
      }
    },
  },
}
