#!/usr/bin/env zsh
#MISE description="Run pre-commit linters"
#USAGE arg "<files>..."
set -eu

fpath=(~/.shellrc/zshrc.d/functions $fpath)
autoload -Uz iterm2_progress iterm2_badge iterm2_notify

iterm2_badge "lint"
iterm2_progress -i

_cleanup_done=0
_lint_cleanup() {
  (( _cleanup_done )) && return
  _cleanup_done=1
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    iterm2_progress -e
    iterm2_notify "lint failed"
  else
    iterm2_progress -c
    iterm2_notify "lint complete"
  fi
  iterm2_badge -c
}
trap _lint_cleanup EXIT INT TERM HUP

if [ ${#} -gt 0 ]; then
    yadm enter pre-commit run --files "$@"
else
    yadm enter pre-commit run --all-files
fi
