#!/usr/bin/env sh
#MISE description="Fetch and hard-reset dotfiles to origin/master"
set -eu

if [ -n "$(yadm status -s)" ]; then
    printf "This will discard local dotfile changes. Continue? [y/N] "
    read -r reply
    case "${reply}" in
        [yY]|[yY][eE][sS]) ;;
        *) exit 1 ;;
    esac
fi
yadm fetch
yadm reset --hard origin/master
